language: node_js

install: npm install -g jshint

script: jshint *.js

before_deploy:
  - export RELEASE_PKG_FILE=$(cat version)
  - echo "deploying $RELEASE_PKG_FILE to Github releases"

deploy:
  provider: releases
  api_key:
    secure: oQVFKWNdC63fPcDV61XpsAmLYwGWNDE5upoqdfzKVhRBa20R57V5QdBO/uxOpEvO7B+eVl1o18C39VrgZqhNfPW4DNWA4h2PhJLMK3u00iErG/sa33BiSxy0CvqE/U1SqHmG6+MyNE/yjcgSG8da88ztOcYduyC2I5TGP1LqOb+NiEOMfcq2mBuFDTCjR00xZtGyt+lU44uObuJGujemCSQO51y394fAgJkvoQxiXT1ijeJ8KLPbMF0g0O5uJiEDLVdQ7pKJj02G9f7nZrdynJsRqenn2J+jA1wIBvfhJuD7qhhUYnT85Y0PODmhUIkkBxPhj+s+Krzq6wmmUl8q1iN33q3nP9e0ZEzcPIa48ClJM1QGZ+iuUwl/a2CxSayZ4Hj8Glj6ikkqvtukOEksfw5wwDA0/wrckpx/Zp+EQwxTWi6hlspLghiEgV1/JDGT4imJBUjvwSgD5sZS1hD3BP/hNDFvK2mtyOkRpg6359l7rDkc+e3QIau7hB63+t+yvUtrwqsXhahX71hHD8fRO81xsBLcEhfdnlUF9AAzLAVBMnEEszsFmAkSFdjR3o0w7T+zZ3Cn6HXDGBcr8BWlml5mHB4JrFNbwkcL/5s1x08bwTqlpTQD0HxqAc6uPIOf815kbKfezmveHdUuvyZFQgepPoNAlEtJDIWe6zf2Tjs=
  file: "space-${RELEASE_PKG_FILE}.zip"
  skip_cleanup: true
  file_glob: true
  on:
    repo: Dev-Crea/space
    tags: true

notifications:
  email:
    recipients:
      - secure: KnsITm4cIac+/B0CVIjcUTFgTBkuJk6HZv/4GwnHy6lRYvkwe2IYnLXpgDsVhR/SjiBGAoFTZb1uJfu5pfwTh/+eQmg4Xwbffna1fVSVfFyWgG9eyYm2WdWSAo7gRfFMT7q7kLw5LIUlz+sq0T0wKcXyMMf9eWKngOKuEDtci2D9gpfAlu5Cx8zVn+zAHPGJLg7omn748lrjZSowipgyI7lI4rt+wfDY1UzTIUac37adIYz4l9P5g2CEf71D1R2yjtBR5gdWGzknxjof9+NwiDGnII9JKeQTGOO9cTYnOhcDf4RScRDZxPhW8ULYbcZN8OHkcz7LeYhKGQvrP5LEjNJC2KPtF8GttNdvLU6ZWNkm8EzdN5bIzdwO8sNyOzAc6mK5AOV1Um8aHr02Lp7RgBi9u3vVH4as5q/b+wAWZY1C1eoQxVuXOdtxvkfh6QquvKo1miClNKzu/WINzftvxzSG1thLwT7eKFDA/KMD3lh75J6tKrcw9kZGWI1X4hudgVvsnXDMMYGYPXfYnK7tDyFLc/ekqLkiRmukFDhhyc75Bq5xFVXRd2cbCSbwnmQe7lNzwxfGI329WVefczX3DwrD9WG2SbYe7SxZVmaX5lh39QrX9F/sHocpE8+bni+DiBI6yHeXPMYu8zycIvqvWiOI3xYm1KG0EpzUgqcxxL8=
    on_success: never
    on_failure: always
